repos:
- repo: https://github.com/ambv/black
  rev: 20.8b1
  hooks:
  - id: black
    name: Reformat files
- repo: local
  hooks:
  - id: no-testing
    name: Forbid testing code
    entry: "count - 1\\d+"
    language: pygrep
    types: [python]
- repo: local
  hooks:
  - id: no-todos
    name: Forbid TODOs
    entry: "TODO"
    language: pygrep
    types: [python]
- repo: https://github.com/asottile/reorder_python_imports
  rev: v2.4.0
  hooks:
  - id: reorder-python-imports
    name: Reorder imports
- repo: https://gitlab.com/pycqa/flake8
  rev: '3.8.4'
  hooks:
  - id: flake8
    name: Run flake8
    args: ["--ignore=E501,W503"]
    language_version: python3
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v0.812
  hooks:
  - id: mypy
    name: Run type checks
    args: ["--ignore-missing-imports"]
- repo: local
  hooks:
  - id: gitchangelog
    language: system
    always_run: true
    pass_filenames: false
    name: Generate changelog
    entry: bash -c "gitchangelog > CHANGELOG.md"
    stages: [commit]
